#ifndef ENUM_H
#define ENUM_H

typedef enum
{
    ADD_STUDNET,
    MODIFY_STUDENT,
    DELETE_STUDENT,
    ADD_STUDENT_COURSE,
    MODIFY_STUDENT_COURSE,
    DELETE_STUDENT_COURSE,
} Operation;

typedef enum
{
    ADD_STUDENT_SUCCESS,
    ADD_STUDENT_FAILURE,
    MODIFY_STUDENT_SUCCESS,
    MODIFY_STUDENT_FAILURE,
    DELETE_STUDENT_SUCCESS,
    DELETE_STUDENT_FAILURE,
    ADD_STUDENT_COURSE_SUCCESS,
    ADD_STUDENT_COURSE_FAILURE,
    MODIFY_STUDENT_COURSE_SUCCESS,
    MODIFY_STUDENT_COURSE_FAILURE,
    DELETE_STUDENT_COURSE_SUCCESS,
    DELETE_STUDENT_COURSE_FAILURE,
} Response;

#endif
