#ifndef ENUM_H
#define ENUM_H

typedef enum
{
    ADD_STUDNET,
    MODIFY_STUDENT,
    DELETE_STUDENT,
    ADD_STUDENT_COURSE,
    MODIFY_STUDENT_COURSE,
    DELETE_STUDENT_COURSE,
} Operation;

typedef enum
{
    ADD_STUDENT_SUCCESS,
    ADD_STUDENT_FAIL_STUDENT_EXISTS,

    MODIFY_STUDENT_SUCCESS,
    MODIFY_STUDENT_FAIL_NO_STUDENT,

    DELETE_STUDENT_SUCCESS,
    DELETE_STUDENT_FAIL_NO_STUDENT,

    ADD_COURSE_SUCCESS,
    ADD_COURSE_FAIL_NO_STUDENT,
    ADD_COURSE_FAIL_COURSE_EXISTS,

    MODIFY_COURSE_SUCCESS,
    MODIFY_COURSE_FAIL_NO_STUDENT,
    MODIFY_COURSE_FAIL_NO_COURSE,

    DELETE_COURSE_SUCCESS,
    DELETE_COURSE_FAIL_NO_STUDENT,
    DELETE_COURSE_FAIL_NO_COURSE
} Response;

extern const char *responseMessages[];

#endif
